import type {
  ContatoEmpresa, EmpresaDossie, PersonaCliente, ProdutoCliente as _P, ProdutoEmpresa,
  ReuniaoEmpresa, EventoTimeline, DocumentoEmpresa, EscopoContrato,
} from "@/lib/types";

/**
 * Carteira real da Conteúdo Martech, importada do Portal MarTech.
 * Campos que não existiam na origem (CNPJ, endereço) ficam em branco para
 * serem preenchidos pelo time.
 */

export const empresasImportadas: EmpresaDossie[] = [
  {
    id: "emp-01",
    razao_social: "FIEG",
    nome_fantasia: "FIEG",
    cnpj: "",
    segmento: "Setor Público",
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "onboarding",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: "2026-05-11",
    created_at: "2026-05-11T17:02:46.303077+00:00",
    ativo: true,
  },
  {
    id: "emp-02",
    razao_social: "SAEA",
    nome_fantasia: "SAEA",
    cnpj: "",
    segmento: "Colégio",
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "ativo",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: null,
    created_at: "2026-04-30T17:20:54.404748+00:00",
    ativo: true,
  },
  {
    id: "emp-03",
    razao_social: "Colégio Friburgo",
    nome_fantasia: "Colégio Friburgo",
    cnpj: "",
    segmento: null,
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "ativo",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: null,
    created_at: "2026-05-06T17:19:41.6615+00:00",
    ativo: true,
  },
  {
    id: "emp-04",
    razao_social: "Casinha Pequenina",
    nome_fantasia: "Casinha Pequenina",
    cnpj: "",
    segmento: null,
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "ativo",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: null,
    created_at: "2026-05-06T18:04:28.116548+00:00",
    ativo: true,
  },
  {
    id: "emp-05",
    razao_social: "EDUCON",
    nome_fantasia: "EDUCON",
    cnpj: "",
    segmento: null,
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "encerrado",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: null,
    created_at: "2026-05-06T13:56:00.973322+00:00",
    ativo: true,
  },
  {
    id: "emp-06",
    razao_social: "SENAI-MS",
    nome_fantasia: "SENAI-MS",
    cnpj: "",
    segmento: null,
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "ativo",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: null,
    created_at: "2026-05-15T19:58:26.525147+00:00",
    ativo: true,
  },
  {
    id: "emp-07",
    razao_social: "Unisagrado",
    nome_fantasia: "Unisagrado",
    cnpj: "",
    segmento: "Educação",
    site: null,
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "onboarding",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: null,
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: "2026-08-13",
    created_at: "2026-08-13T22:44:57.338606+00:00",
    ativo: true,
  },
  {
    id: "emp-08",
    razao_social: "UCDB",
    nome_fantasia: "UCDB",
    cnpj: "",
    segmento: "Universisade",
    site: "https://site.ucdb.br/",
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: "Campo Grande",
    estado: "MS",
    status: "onboarding",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: "Campo Grande",
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: "2024-09-01",
    created_at: "2026-05-11T14:56:50.705469+00:00",
    ativo: true,
  },
  {
    id: "emp-09",
    razao_social: "ESEG",
    nome_fantasia: "ESEG",
    cnpj: "",
    segmento: "Ensino Superior",
    site: "https://eseg.edu.br/",
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: "São Paulo",
    estado: "SP",
    status: "ativo",
    responsavel_id: null,
    observacoes: "Ensino superior com a comunicação premium, para ativar ",
    instagram: "https://www.instagram.com/eseg_oficial/",
    linkedin: "https://www.linkedin.com/school/faculdadeeseg/",
    regiao: "São Paulo | Capital",
    elevator_pitch: null,
    contrato_tipo: "Contrato de 5 meses",
    contrato_vigencia: "Encerra em agosto",
    servicos_contratados: "Performance e SEO",
    entrada: "2025-10-06",
    created_at: "2026-08-17T17:38:39.904853+00:00",
    ativo: true,
  },
  {
    id: "emp-10",
    razao_social: "UniProjeção",
    nome_fantasia: "UniProjeção",
    cnpj: "",
    segmento: "Ensino Superior",
    site: "https://processoseletivo.uniprojecao.edu.br/",
    cep: null,
    logradouro: null,
    numero: null,
    complemento: null,
    bairro: null,
    cidade: null,
    estado: null,
    status: "ativo",
    responsavel_id: null,
    observacoes: null,
    instagram: null,
    linkedin: null,
    regiao: "Brasília - DF",
    elevator_pitch: null,
    contrato_tipo: null,
    contrato_vigencia: null,
    servicos_contratados: null,
    entrada: "2026-08-27",
    created_at: "2026-08-27T12:50:34.569201+00:00",
    ativo: true,
  },
];

export const contatosImportados: ContatoEmpresa[] = [
  { id: "ct-01", empresa_id: "emp-08", nome: "Ariane Pina", cargo: "Gerente de Marketing", email: null, telefone: null, linkedin: null, area: "Marketing", principal: true },
  { id: "ct-02", empresa_id: "emp-09", nome: "Elaine", cargo: "Gestora Geral", email: "elaine.senatore@eseg.edu.br ", telefone: "+55 11 94901-5203", linkedin: null, area: null, principal: true },
  { id: "ct-03", empresa_id: "emp-09", nome: "Stela", cargo: "Coordenadora de Marketing", email: "stela.sebastiao@eseg.edu.br ", telefone: "+55 11 98284-2783", linkedin: null, area: "Marketing", principal: false },
  { id: "ct-04", empresa_id: "emp-01", nome: "Amanda", cargo: null, email: null, telefone: null, linkedin: null, area: null, principal: true },
  { id: "ct-05", empresa_id: "emp-07", nome: "Karen", cargo: null, email: null, telefone: null, linkedin: null, area: null, principal: true },
  { id: "ct-06", empresa_id: "emp-10", nome: "Amanda Marot", cargo: null, email: null, telefone: null, linkedin: null, area: null, principal: true },
];

export const personasImportadas: PersonaCliente[] = [
  { id: "pers-01", empresa_id: "emp-08", nome: "teste", cargo: "teste", faixa_etaria: "teste", segmento: "test", objetivos: null, dores: null, objecoes: "test", gatilhos: null, canais: null, tipo_conteudo: null, consciencia: null, conteudo_ideal: null },
  { id: "pers-02", empresa_id: "emp-05", nome: "Mariana, 35 anos", cargo: "Gestor - Carreira", faixa_etaria: null, segmento: "MBA", objetivos: "Busca uma promoção para uma posição de liderança executiva. Quer desenvolver habilidades estratégicas e de liderança para gerenciar grandes equipes e projetos complexos. Deseja expandir sua rede de contatos profissionais, conectando-se com outros executivos e líderes do setor. Quer se manter atualizada com as últimas tendências e melhores práticas em gestão e tecnologia.", dores: "Sente que sua carreira está parada e precisa de um diferencial para se destacar. Percebe que precisa aprimorar suas habilidades de tomada de decisão e gestão estratégica. Falta de conhecimento em novas tendências: sente-se desatualizada em relação às últimas tendências e tecnologias do mercado.", objecoes: null, gatilhos: null, canais: "Instagram, WhatsApp e LinkedIn", tipo_conteudo: "Espera aprender sobre as últimas tendências em gestão e tecnologia. Prefere uma abordagem prática que possa aplicar diretamente em seu trabalho. Busca oportunidades para interagir com outros profissionais e líderes do setor. Espera receber orientação e suporte de professores e mentores experientes.", consciencia: "meio", conteudo_ideal: "Espera aprender sobre as últimas tendências em gestão e tecnologia. Prefere uma abordagem prática que possa aplicar diretamente em seu trabalho. Busca oportunidades para interagir com outros profissionais e líderes do setor. Espera receber orientação e suporte de professores e mentores experientes." },
  { id: "pers-05", empresa_id: "emp-02", nome: "Andrea", cargo: "Gerente de RH", faixa_etaria: null, segmento: "Decisor", objetivos: "teste", dores: "teste", objecoes: "tests", gatilhos: null, canais: "test", tipo_conteudo: "ttes", consciencia: "fundo", conteudo_ideal: "ttes" },
  { id: "pers-08", empresa_id: "emp-02", nome: "Maria", cargo: "Estudante", faixa_etaria: null, segmento: "Influenciador", objetivos: null, dores: null, objecoes: null, gatilhos: null, canais: null, tipo_conteudo: null, consciencia: "topo", conteudo_ideal: null },
];

export const produtosImportados: ProdutoEmpresa[] = [
  { id: "prod-01", empresa_id: "emp-08", nome: "Graduação ", categoria: null, descricao: null, publico: null, ticket_medio: null, meta_comercial: null, diferenciais: null, dores_resolvidas: null, regiao: null, status: "ativo" },
  { id: "prod-02", empresa_id: "emp-08", nome: "Pós-Graduação", categoria: null, descricao: null, publico: null, ticket_medio: null, meta_comercial: null, diferenciais: null, dores_resolvidas: null, regiao: null, status: "ativo" },
  { id: "prod-03", empresa_id: "emp-08", nome: "Mestrado e Doutorado", categoria: null, descricao: null, publico: null, ticket_medio: null, meta_comercial: null, diferenciais: null, dores_resolvidas: null, regiao: null, status: "ativo" },
  { id: "prod-04", empresa_id: "emp-09", nome: "Cursos Graduação", categoria: "Bacharelado", descricao: "Cursos de bacharelado:\n\nAdministração - Diurno e Noturno\nDireito - Diurno e Noturno\nEconomia - Diurno e Noturno\n", publico: "Jovens formandos recentes - Ensino Médio", ticket_medio: "2.4", meta_comercial: "Conversão de um público premium e abastado altamente qualificado, formado principalmente por estudantes de escolas de referência em São Paulo, que buscam uma formação sólida, exigente e conectada às grandes empresas e oportunidades do mercado, indo além da formação acadêmica tradicional.", diferenciais: "Ensino rigoroso e de alta qualidade, com forte exigência acadêmica e foco na formação de profissionais preparados para os desafios reais do mercado.\nForte conexão com o mercado e com grandes empresas, aproximando os alunos de profissionais, executivos e referências de suas áreas de atuação.\nFormação orientada à empregabilidade e à construção de carreiras de alto nível, com alunos inseridos em grandes empresas e ambientes profissionais relevantes.\nConteúdos atualizados e alinhados às demandas do mercado, combinando conhecimento técnico, visão estratégica e aplicação prática.\nPresença de grandes nomes do mercado em aulas, encontros, palestras e eventos, proporcionando contato direto dos alunos com profissionais de referência.\nConstrução de uma rede de relacionamento qualificada, conectando alunos, professores, executivos e empresas.\nExperiência acadêmica que vai além da sala de aula, com eventos e iniciativas que aproximam o aluno do mercado e ampliam sua visão sobre carreira e negócios.\nPosicionamento e experiência voltados a um público que busca alta performance, excelência e diferenciação profissional.", dores_resolvidas: null, regiao: "São Paulo", status: "ativo" },
];

export const reunioesImportadas: ReuniaoEmpresa[] = [
  { id: "reu-01", empresa_id: "emp-08", data: "2026-05-04", tema: "Apresentação de 26A", participantes: "karen, lucas, matheus, ariane", responsavel: "Karen", status: "realizada", proximos_passos: "tesste", ata: "teste" },
  { id: "reu-02", empresa_id: "emp-09", data: "2026-08-14", tema: "Planejamento Reverso - Conteúdo Martech", participantes: null, responsavel: "Amanda", status: "realizada", proximos_passos: "Foi repassado o cronograma reverso para implementação das campanhas do intake 2027.1 que inicia dia 31 de agosto. https://docs.google.com/document/d/1b092tVR3-OyZF9m63PN0rEOIq2lh4z7OxS2CZYPs5cY/edit?usp=sharing", ata: null },
];

export const timelineImportada: EventoTimeline[] = [
  { id: "tl-01", empresa_id: "emp-09", data: "2026-08-19", titulo: "Solicitações - Planejamento Intake 2027.1", conteudo: "- Solicitado inclusão na comunicação do logo de 20 anos de ESEG\n- Solicitação de divisão de verba para incluir Podcast\n- Solicitação para inclusão da campanha de pais. " },
];

export const documentosImportados: DocumentoEmpresa[] = [
  { id: "doc-01", empresa_id: "emp-04", nome: "[CASINHA] Planejamento Intake 2027.1 [falta validação final] ", tipo: "planejamento", data: "2026-08-14", link: "https://canva.link/20sxh0lhejpi6z6" },
];

export const escoposImportados: EscopoContrato[] = [
  { id: "esc-01", empresa_id: "emp-02", escopo: "inbound", modelo_cobranca: "projeto", observacoes: null, inicio: "2026-04-30" },
  { id: "esc-02", empresa_id: "emp-04", escopo: "inbound", modelo_cobranca: "projeto", observacoes: null, inicio: "2026-05-06" },
  { id: "esc-03", empresa_id: "emp-06", escopo: "inbound", modelo_cobranca: "mensal", observacoes: null, inicio: "2026-05-15" },
  { id: "esc-04", empresa_id: "emp-08", escopo: "inbound", modelo_cobranca: "mensal", observacoes: null, inicio: "2026-06-30" },
  { id: "esc-05", empresa_id: "emp-05", escopo: "inbound", modelo_cobranca: "mensal", observacoes: null, inicio: "2026-05-06" },
  { id: "esc-06", empresa_id: "emp-03", escopo: "inbound", modelo_cobranca: "projeto", observacoes: null, inicio: "2026-05-06" },
  { id: "esc-07", empresa_id: "emp-07", escopo: "inbound", modelo_cobranca: "mensal", observacoes: null, inicio: "2026-08-01" },
];